### ISSUE TITLE
Timeline Issues

### ISSUE THREAD

**Issue by calxus** [kaffo/multi-device-audio-project#11]
[X]The timeline needs to be scaled down so it only shows the lower half of the default TimelineJS view
[X]integrated to the main page
[X]Needs to be able to dynamically load data it is fed fitting in with django template system

**Comment by ppyordanov** [comment]
forgot to close that

**Comment by allyjweir** [comment]
[ ]The timeline needs to be scaled down so it only shows the lower half of the default TimelineJS view
[ ]integrated to the main page
[ ]Needs to be able to dynamically load data it is fed fitting in with django template system

**Comment by ppyordanov** [comment]
Will look into that ASAP.

**Comment by ppyordanov** [comment]
This timeline is giving me headaches for blocking other javascript on the page or not loading in the presence of the integrated map

**Comment by ppyordanov** [comment]
I integrated the timeline on the home page and packed the javascript neatly into a separate script.

**Comment by ppyordanov** [comment]
ALPHA build is done.
