### ISSUE TITLE
Dynamic django templates

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#13]
need to replace the static html pages that are currently in the application with these.

Chapter 5/6 of Tango with Django

**Comment by kaffo** [comment]
Surely less a case of replacing and more a case of editing the current pages to use the template-able parts? (Like the menu bar, user bar etc)

**Comment by kaffo** [comment]
Please can we get this sorted, it will make life so much easier not having to change 4 menu bars. I can then add the login junk if it's templatable.

**Comment by calxus** [comment]
I'll get this completed by the end of tomorrow.

**Comment by calxus** [comment]
As I can't sleep. This issue has been sorted.

**Comment by calxus** [comment]
Got over excited and closed the issue prematurely. Fixed a bug with highlighting current page, runs smoothly now however.
