### ISSUE TITLE
map issues

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#15]
[ ]Polyline needed for arrray of locations
[ ]Put markers where there are images on the polyline
[ ]Replace default marker with projects logo

**Comment by calxus** [comment]
Will get working on this now

**Comment by calxus** [comment]
Got the polyline working fine, but untill we can get some test lat/lon arrays in the database it cannot be properly tested

**Comment by calxus** [comment]
replaced the default marker with the project logo as well

**Comment by allyjweir** [comment]
Make some mock data and load it into the server using a script or manually
with the mySQL admin interface.

**Comment by kaffo** [comment]
Quick python script made by copy pasting the stuff from process will have mock data in minutes.

**Comment by calxus** [comment]
perfect cheers i'll look at that now

**Comment by calxus** [comment]
I found a good djanco article for sorting out the many locations to one recording. So i'll follow that and hopefuly should work

**Comment by calxus** [comment]
https://docs.djangoproject.com/en/1.4/topics/db/examples/many_to_one/

**Comment by calxus** [comment]
[X]Polyline needed for arrray of locations
[ ]Put markers where there are images on the polyline
[X]Replace default marker with projects logo

2 out of 3 completed

**Comment by ppyordanov** [comment]
Just to clarify something. The timeline shows the recordings as objects and lets the user switch between them, if we are to make photo/tags popups of grouped recordings' timelines we probably need to consider using something like https://developers.soundcloud.com/docs/api/sdks#javascript which at the moment I dont see how will work like buzz.

**Comment by calxus** [comment]
The photos will be on the map, not on the timeline I think. The timeline, is mainly just a visual representation of the time in which the recordings were taken. 
I could be wrong with this, but that is what I thought.

**Comment by calxus** [comment]
[X]Polyline needed for arrray of locations
[X]Put markers where there are images on the polyline
[X]Replace default marker with projects logo

3 out of 3 completed

link to commit 4e1bcd5f4f6d865574b1d7fa0050ae19f187bb7f

There is still a lot of inadequacies with these implementations but I hopw over time they will be ironed out.

**Comment by calxus** [comment]
Thought I should say:
The map gets the information fine, the grey area lies in how it will be processed and uploaded into the database, this issue however will be threshed out when it becomes more clear how the information will be uploaded from the mobile device. 
But as this does not come under the heading of map issues this issue is now completed. And the grey area will be cleared in a separate issue.
