### ISSUE TITLE
Start view

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#19]
It would be a really nice feature if we could get the Google Maps to request the user's location through the browser and then have a higher zoom level around their location.

**Comment by calxus** [comment]
This was completed using html5 geolocation fb76888

**Comment by allyjweir** [comment]
Looks good. Would be great if it showed the user's current location with a marker or dot of some form.

**Comment by calxus** [comment]
I think a dot is the best course of action here, will implement this today. Pretty sweet idea actually

**Comment by calxus** [comment]
This has been completed, blue dot was a good idea. Works really well imo. a4aa57a740

**Comment by allyjweir** [comment]
Need to re-draw the dot as the user zooms in and out. currently it doesnt

**Comment by calxus** [comment]
Rather than redrawing which isn't the issue, this was more to do with a problem of where the anchor of the dot is, this was fixed however by specifying the anchor.
