### ISSUE TITLE
Working Query from Front End

### ISSUE THREAD

**Issue by kaffo** [kaffo/multi-device-audio-project#2]
We have a working RESTful API for grabbing data from the backend database (/webapp/getdata<box>) which will return a whole bunch of information in JSON. Someone needs to get the bounding box of the map using lon and lat then pass that to the gatdata function so we can return the JSON with the details.

**Comment by calxus** [comment]
I will get working on this

**Comment by calxus** [comment]
can query the database now with

$.get(
        "/webapp/getdata:" + swLat + ":" + swLng + ":" + neLat + ":" + neLng,
        function(data) {
}

**Comment by calxus** [comment]
and lat/lng is obtained with:

var sw = bounds.getSouthWest();
var ne = bounds.getNorthEast();
var swLat = sw.lat();
var swLng = sw.lng();
var neLat = ne.lat();
var neLng = ne.lng();
