### ISSUE TITLE
Select recordings in view button issues

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#20]
this button would be better if it could float over the map. It needs reworded to make it clear that it will be the ones in view that it selects "Select all in view" would do. 
Also a button to clear it would be REALLY great

**Comment by allyjweir** [comment]
Or even a separator in the side menu and the clear button in there too if button over map is too much hassle

**Comment by calxus** [comment]
To make it float over the map is too messy imo. Making it more clear in the side menu is a safer bet, as was mentioned. 
Will work on this tomorrow and will implement the clear button

**Comment by calxus** [comment]
I added a de-select option, also made the select and de-select buttons more obvious on the page. f917960c69

**Comment by allyjweir** [comment]
sweet
