### ISSUE TITLE
Timeline on the homepage

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#23]
This needs integrated to the main page and user page. Don't care how ugly it is, just needs to be there. It is a key part of the project. Fiddle with some jQuery and JS and should be pretty trivial

**Comment by ppyordanov** [comment]
It is trivial but there is some javascript conflict. Will fiddle with the code again now.

**Comment by ppyordanov** [comment]
Keeps saying 'loading timeline' on the home page and won't work, very frustrating.

PS: I actually sent mr @Gremuska (or whatever) an email a while back and posted on their forum about this issue - this was last time when I tried to make it work, but I have received no response from them to date.

**Comment by ppyordanov** [comment]
Thread link: https://knightlab.zendesk.com/entries/31584053-Timeline-script-blocks-other-scripts

Depending on where in the html code I insert the link to the external tl.js file either the map does not show or the timeline itself cannot load.

**Comment by calxus** [comment]
this still blocks the javascript on the map.

also it returns all pins, as opposed to just those in view.

**Comment by ppyordanov** [comment]
Ok, I've done everything I thought of, ran out of ideas.

PS: Probably what we could do is have a SYNC button (on the HomePage) to synchronise either all visible pins on the map or only those that have been selected/ marked with different filters (like location, tag, etc) this button will send the user to a page with the timeline showing all the selections with their location and play button with the synchronized playback

**Comment by kaffo** [comment]
Yay, workabouts disguised as features!

**Comment by ppyordanov** [comment]
Nope, this is a problem that needs fixing. Do you have ideas how to fix it?

**Comment by calxus** [comment]
Though there has been progress made in this issue, I find markers show on chrome but not on Firefox. I don't know yet whether this is to do with a conflict with the timeline, or for something completely unrelated.

If it does show to be unrelated during testing tomorrow, a separate issue can be made for it.

**Comment by calxus** [comment]
I spent a few hours trying to find the problem with this, to little or no avail. When the Timeline is placed on the homepage, I get an error on my map when initializing markers alternating between:
InvalidValueError: setPosition: in property lat: not a number
InvalidValueError: setMap: not an instance of Map
There might be something with googlemaps in the timeline causing mischief, but I can't say for sure.

**Comment by calxus** [comment]
![image](https://f.cloud.github.com/assets/5579497/2236768/2bb2c16a-9b6b-11e3-8ecc-cbddfa4e2a6d.png)

I tried this timeline and it works with no conflicts, plus you don't get that annoying top part at the top. Either I could get this working or another person could work with it. But I think it would be the quickest and most effective way to get things moving on this.

http://simile.mit.edu/timeline/docs/create-timelines.html

**Comment by ppyordanov** [comment]
I think you need to check this out: http://stackoverflow.com/questions/20585055/uncaught-invalidvalueerror-setposition-not-a-latlng-or-latlngliteral-in-prope . I will try to see what else in your code might be causing the conflict.

**Comment by calxus** [comment]
I spent hours trying to fix the problem with the timeline last night, and have surprisingly thought of consulting stackoverflow already. The idea of changing the timeline does not come lightly, and it's not a problem with the timeline per se. It's just integrating has been an issue from the beginning, and very little has been achieved in doing this. I think it might be time to call it a day, and try another solution.

**Comment by allyjweir** [comment]
I have to agree with Gordon here, it has been a long standing issue. We _HAVE_ to be code complete by Sunday night. There are other assessments due and an entire dissertation to write. 
I understand any frustration at losing work but there comes a time when we need to cut losses and find workable solutions with the given timescale.

**Comment by calxus** [comment]
After all that, it was sorted. 

It occurred as a conflict between my map, and the maps that were initiated in the timeline. So when Peter removed the link to google maps from the timeline (which were not shown anyway, so no loss of functionality) This resolved the problem.
