### ISSUE TITLE
Get upload working

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#24]
It is running into an I/O Error. Need to fix this. Also it would be great if we could somehow setup a response to confirm a successful upload from mobile. Not really sure how to do this. If anyone has an idea it has a bounty of a pint

**Comment by calxus** [comment]
sorted the error in upload. If anymore errors rear their head (Which knowing my luck they will) we can reopen this again. But as of now Ignorance is Bliss.

**Comment by calxus** [comment]
There needs to be checks that a file with the same name can not be uploaded twice, or else find another way to reference a recording besides its fileName

**Comment by calxus** [comment]
checks to make sure there is not already a file with the same name in the db. if so returns an error page a62bd2b5f8

**Comment by allyjweir** [comment]
Getting a new upload error, huzzah!
![screen shot 2014-02-21 at 14 35 38](https://f.cloud.github.com/assets/3640069/2230654/8c5c30ac-9b05-11e3-949d-3dd86089e4ce.png)

Also look in this dropbox folder for test files:
https://www.dropbox.com/sh/s26c6zlz9a8nr12/oi4-uTOC8_

**Comment by calxus** [comment]
This is conversion
