### ISSUE TITLE
Info Window

### ISSUE THREAD

**Issue by calxus** [kaffo/multi-device-audio-project#25]
The info window that appears when you click a marker  needs to be made pretty

**Comment by allyjweir** [comment]
Made this a high priority as it is something John actively called out as needing improved. will come up with a mockup and post a picture to work from

**Comment by calxus** [comment]
Working on this now, so that it is at least customised and info window opens at a consistent height and width. But would be helpful to see the mockup to work from as my designing skills are somewhat lacking.

**Comment by calxus** [comment]
going to use an infobubble
http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobubble/examples/example.html/

**Comment by calxus** [comment]
![image](https://f.cloud.github.com/assets/5579497/2190885/bd61b93e-9834-11e3-89e5-7979d3bc8689.png)

An example of the infoBubble, if people could give their comments on it.

**Comment by allyjweir** [comment]
I like it

**Comment by ppyordanov** [comment]
Looks good ;)

**Comment by calxus** [comment]
commited this update 1c153ec
