### ISSUE TITLE
Conversion after upload

### ISSUE THREAD

**Issue by ppyordanov** [kaffo/multi-device-audio-project#26]
A file upload should automatically trigger file conversion from .3gp to .ogg

// @allyjweir, @gtadam and Kaffse have also helped with this ( @Kaffse contacted support to install ffmpeg)

**Comment by ppyordanov** [comment]
I have implemented this functionality. What remains now is to test untar-ing archives as I think there might be some bugs as initially the function was designed for .3gp files.

**Comment by ppyordanov** [comment]
It might have to do something with upload.

PS: yesterday even after I dropped my tables still did not manage to make upload working on localhost (it just does not save to the database, I might have missed something).

Upload problem introduced here:
https://github.com/Kaffse/multi-device-audio-project/issues/30

**Comment by calxus** [comment]
Re-opened as to the best of my knowledge conversion is still to be implemented into the upload functionality

**Comment by ppyordanov** [comment]
Turns out that the FFmpeg version we have on the server is deprecated:

**\* THIS PROGRAM IS DEPRECATED ***
This program is only provided for compatibility and will be removed in a future release. Please use avconv instead.
audio.3gp: Invalid data found when processing input

It was working about 2 weeks ago.

http://avidemux.org/smuf/index.php?topic=11407.0

http://ubuntuforums.org/showthread.php?t=2007808

**Comment by allyjweir** [comment]
Files for testing with https://www.dropbox.com/sh/s26c6zlz9a8nr12/oi4-uTOC8_

**Comment by calxus** [comment]
@allyjweir 

Getting a new upload error, huzzah!
https://f.cloud.github.com/assets/3640069/2230654/8c5c30ac-9b05-11e3-949d-3dd86089e4ce.png

Also look in this dropbox folder for test files:
https://www.dropbox.com/sh/s26c6zlz9a8nr12/oi4-uTOC8_

**Comment by ppyordanov** [comment]
Oops that's my fault imported subprocess as sp and forgot about it. // fixed

**Comment by calxus** [comment]
As ffmpeg seems to be deprecated, I think avconv might be the way to go here. I will give it a shot tomorrow.

**Comment by ppyordanov** [comment]
There is some problem with the .3gp files being invalid, VLC plays them but buzz does not recognise the ogg after conversion.


super@penida:/workspace/build$ avconv -i audio.3gp
avconv version 0.8.10-4:0.8.10-0ubuntu0.12.04.1, Copyright (c) 2000-2013 the Libav developers
  built on Feb  6 2014 20:56:59 with gcc 4.6.3
audio.3gp: Invalid data found when processing input

(avconv cannot recognise the input file, but still converts it)

**Comment by ppyordanov** [comment]
For comparison I downloaded another 3gp file which is recogised without problems: 

///
super@penida:/workspace/build$ avconv -i HelixMobileProducer_test5_3GPv5_MPEG4SP_24bit_176x144_AR1.22_30fps_K               Fx_320kbps_AAC-LC_Mono_11025Hz_24kbps.3gp
avconv version 0.8.10-4:0.8.10-0ubuntu0.12.04.1, Copyright (c) 2000-2013 the Libav developers
  built on Feb  6 2014 20:56:59 with gcc 4.6.3
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x13df7a0] max_analyze_duration reached
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'HelixMobileProducer_test5_3GPv5_MPEG4SP_24bit_176x144_AR1.22_30fps_K               Fx_320kbps_AAC-LC_Mono_11025Hz_24kbps.3gp':
  Metadata:
    major_brand     : 3gp5
    minor_version   : 0
    compatible_brands: 3gp5isom
    creation_time   : 2008-11-30 19:57:42
  Duration: 00:06:28.05, start: 0.000000, bitrate: 113 kb/s
    Stream #0.0(und): Video: mpeg4 (Simple Profile), yuv420p, 176x144 [PAR 1:1 DAR 11:9], 79 kb/s, 15 fps, 15                tbr, 90k tbn, 30k tbc
    Metadata:
      creation_time   : 2008-11-30 19:57:42
    Stream #0.1(und): Data: rtp  / 0x20707472, 4 kb/s
    Metadata:
      creation_time   : 2008-11-30 19:57:42
    Stream #0.2(und): Audio: aac, 11025 Hz, mono, s16, 24 kb/s
    Metadata:
      creation_time   : 2008-11-30 19:57:42
    Stream #0.3(und): Data: rtp  / 0x20707472, 3 kb/s
    Metadata:
      creation_time   : 2008-11-30 19:57:42
    Stream #0.4(und): Data: mp4s / 0x7334706D
    Metadata:
      creation_time   : 2008-11-30 19:59:23
    Stream #0.5(und): Data: mp4s / 0x7334706D
    Metadata:
      creation_time   : 2008-11-30 19:59:23

**Comment by ppyordanov** [comment]
Ok after Ally changed the file extensions from .3gp video to .aac audio avconv converts the file successfully. Here is a sample recording from today just uploaded on my profile converted from .aac to .ogg automatically: http://penida.dcs.gla.ac.uk/static/data/matpat123.ogg

!Buzz also supports .aac and plays the files but the convert functionality works and is currently integrated (can later be used to optimize file size during convert, etc)
