### ISSUE TITLE
No map in certain browsers

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#27]
Currently in the lab running it from the server. It doesn't show the map view in Firefox or Chromium. Works in Opera really well.

Works on my Macbook on Chrome. Could everyone give it a quick test on your OS/Browser

**Comment by allyjweir** [comment]
Map isn't showing on Android Chrome either

**Comment by calxus** [comment]
I know the reason for this I think, it is to do with the geolocation. I will need to try and attempt to use geolocation and if not display the map. With a popup telling you how to get your location turned on.

**Comment by allyjweir** [comment]
Sweet.

**Comment by calxus** [comment]
Got this problem fixed it is displaying a map now even if it cannot get the location, though the popup giving you info when it cannot find the location (which you would think would be the easy bit) seems to be proving trickier than I initially thought but I'll try to implement at least some alert that geolocation has failed. And as ally said if people could test it on their browsers and if there is any unexpected behavior just reopen this issue and I'll take a look.
