### ISSUE TITLE
User page

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#28]
This needs some further development:

[] Need to display a list of Users recording
[] Map view showing only the users recordings
[] Timeline of recordings

_Stretch Goals_
- Pretty d3 graphs of when the user most submits. List of stats of most common location etc. Probably a little out of reach but if anyone is really bored in the next 48 hours (not likely)

**Comment by ppyordanov** [comment]
Working on this now and testing it, cannot figure out how to solve the problem as the timeline embed script keeps blocking even buzz. This issue is so frustrating but I should be able to solve it.

**Comment by ppyordanov** [comment]
Argh, this is so frustrating..

**Comment by ppyordanov** [comment]
Still no luck with this..

**Comment by kaffo** [comment]
I assume you saw my code on the user page Peter that pulls the user's recordings?

**Comment by ppyordanov** [comment]
Yes I saw it, will change the page to work with it. There is a bug that I thought I had fixed, but still occurs sometimes - a longer track is not grouped properly by buzz and therefore not played

**Comment by ppyordanov** [comment]
Here is the basic user page prototype - timeline on the right - recording information/ metadata on the left with play buttons to independently play user recordings or download them, etc. More space will be freed for the map on the left.

Note that there is no styling at all - ugly as f*ck - this is a sample which I will style. Just showing here that it pulls data from the backend successfully.

![alt text](http://i61.tinypic.com/vyxzpv.png)

https://www.dropbox.com/s/rte8fr7xa0czozx/user.png

**Comment by allyjweir** [comment]
Could we change the bubble grid to the pureCSS grids for consistency of UI?

**Comment by ppyordanov** [comment]
I just saw them: http://purecss.io/grids/ yeah of course. will do that later today

**Comment by allyjweir** [comment]
Amazing. thanks

**Comment by ppyordanov** [comment]
Here is a quick example of how prototype v2 looks like:

play + download buttons work + the map is integrated// recording selection from the list currently adds file ids to an array and I will fully implement it by the end of this weekend. Also shows the currently synchronised files in the 'Sync at' grid box.

![alt text](http://i59.tinypic.com/70dwlx.png)

**Comment by ppyordanov** [comment]
I have completed the user page. Please log in and test it - upload some recordings and try to play them individually, synchronise them, etc and tell me if there are any bugs/problems.

**Comment by ppyordanov** [comment]
As mentioned above the work on this issue has been completed - the user page displays only the user recordings on the timeline and I think on the map too. There is also a list of user recordings on the right which can be played both individually or synchronised.

If some bugs are found when testing they will be resolved in separate issues. I have some improvement ideas and will create new issues as stretch goals.
