### ISSUE TITLE
Universal play/stop buttons

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#34]
Need this to control the selection

**Comment by calxus** [comment]
Will get this sorted tomorrow should be a breeze with selection working properly.

**Comment by calxus** [comment]
Added the buttons just got to sort out the js

**Comment by calxus** [comment]
Sorted out the js on the map end and it sends the recording id's. Just need the buzz stuff to be sorted

**Comment by calxus** [comment]
This has been added to the map, buzz just needs to be sorted.
