### ISSUE TITLE
Controls for choosing date range of recordings to be shown with select all button

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#35]

**Comment by calxus** [comment]
Although I dont believe this is pressing, it interests me and it seems pretty doable so i'm going to give this a shot tonight.

**Comment by calxus** [comment]
Making good progress on this. I'm using jquery datepicker.

http://jqueryui.com/datepicker/

**Comment by calxus** [comment]
Got this working, it's not very pretty. But if anyone has any ideas for how it should be layed out on the side. I'll be happy to do my best to make it so
