### ISSUE TITLE
Time Selector

### ISSUE THREAD

**Issue by calxus** [kaffo/multi-device-audio-project#42]
Through even a little use it is dawning how naive the datepicker I chose to use is, without the use of a timepicker aswell alongside it. 

To implement this, functionally speaking, I don't think should be too difficult. 

However to lay it out on the ui, might be a little difficult without making it look cluttered.

**Comment by calxus** [comment]
This example shows how I would ideally like to select date and time

http://jonthornton.github.io/jquery-datepair/

**Comment by allyjweir** [comment]
Floating button on top right corner of map which when clicked reveals a
space with time narrowing and tag search.

Or put the button on the menu and the box will appear overlaying the map
etc and goes away when finished with it
