### ISSUE TITLE
Control box

### ISSUE THREAD

**Issue by calxus** [kaffo/multi-device-audio-project#43]
based on idea from comment by ally on Time Selector #42 

"put the button on the menu and the box will appear overlaying the map
etc and goes away when finished with it"

Going to put all map controls in a box that appears over the map when the button is clicked.

**Comment by calxus** [comment]
Created the control box and placed everything inside, the layout is still messed up. But With just a little bit of tweaking. I should get it to be layed out correctly.

**Comment by allyjweir** [comment]
nice work Gordon

**Comment by allyjweir** [comment]
It goes underneath the timeline if the window is small enough. Need to make it the dominant one

**Comment by calxus** [comment]
This box, and the control box has now been made draggable
