### ISSUE TITLE
possibility of user authentication from mobile upload

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#44]
I am looking into the possibility of this allyjweir/mdrs-mobile#29

Not starting on the code now but could someone look into the possibility of the upload page taking a username and password on upload?

I am using this library http://loopj.com/android-async-http/
If you goto the bottom it shows what I would be doing when sending these authentication details.

So yeah, what would it take and how achievable would it be?

**Comment by calxus** [comment]
I could look into this, tomorrow but if anyone get's there first that's and want's to take it off me. That's cool with me. There is the possibility, that if i'm looking into user's with this, that I could pair this up with the avatar.
