### ISSUE TITLE
Front end map gets Buzz to play sound from pin click

### ISSUE THREAD

**Issue by kaffo** [kaffo/multi-device-audio-project#5]
This is a fairly final issue #2 #3 #4 need to be completed for this issue to be completed. We want to click a pin on the map and have Buzz play that sound.

**Comment by calxus** [comment]
I will start on this tonight, If nobody else takes up this ticket first.

**Comment by calxus** [comment]
It works when I run this on a local server but not from the remote server, very infuriating. for some reason /webapp/ is prepended onto the links when I run it on the penida server. I will look at this and give a shot at fixing it later tonight

**Comment by calxus** [comment]
Fixed it!
