### ISSUE TITLE
Recording popup

### ISSUE THREAD

**Issue by allyjweir** [kaffo/multi-device-audio-project#51]
This needs to be consigned to a corner of the map view. otherwise it is obscuring the users view of the trail. Also need a pin for the end point

**Comment by allyjweir** [comment]
z index?

**Comment by allyjweir** [comment]
Also modify the field dates to be a little lighter

**Comment by calxus** [comment]
The z-index was with regards to #43 Control Box where the control box was below the timeline, I also assume that is what you are referring to with the field dates being lighter. 

I will make the popup in the top right hand corner of the screen. But there will not be multiple popups when you click on a number of pins, it will just change if you click on a different one.
This will take a fair bit of work as the infoWindow that appeared when you clicked on a pin was a part of the google maps api, so I am going to have to start from scratch there.

**Comment by calxus** [comment]
forgot to reference commit 0572784

**Comment by calxus** [comment]
If anyone has any comments on how to improve the look of the pop up, just let me know
