### ISSUE TITLE
Make the front end super pretty

### ISSUE THREAD

**Issue by kaffo** [kaffo/multi-device-audio-project#6]
The front end needs to look like the sex. Once it's finished I want to pass out with joy just going to the home page.

**Comment by calxus** [comment]
working on this now, I've got a significantly better menu going. Used from purecss.io

**Comment by calxus** [comment]
Menu is working fine on the page, if you shrink the browser the menu will hide itself unless the browser is once again enlarged or you ask to see the menu. 
It is also a little less offensive on the eyes as compared to the previous ui.

**Comment by calxus** [comment]
this ticket still has a few things to be tweaked

**Comment by calxus** [comment]
This will be an ongoing issue, though imo it will suffice for now.

**Comment by allyjweir** [comment]
[ ]Fix links
[ ]integrate logo
[ ]fix positioning of menu/map on mobile devices
[ ]upload success screen
[ ]User page finished
[ ]Indication that the user is logged in on side menu or top bar

**Comment by allyjweir** [comment]
Logo

https://drive.google.com/file/d/0B2Z3x42UkFznR3FySjJ3eHdGdm1XQjZwQUJ3S1BvdFZneGVn/edit?usp=sharing
https://drive.google.com/file/d/0B2Z3x42UkFznZk5uM25pME4zUl9sMVdPQUJvdTN5Q0wxYmJV/edit?usp=sharing

Also applicable to #15 for replacing default marker

**Comment by calxus** [comment]
Will start tackling these tomorrow

**Comment by ppyordanov** [comment]
Gordon without any offence I suggest making a custom template if we have time and use the Django template structure with integrated context elements. I think that we are going to get extra points for not using a downloaded template and I am ready/ eager to help with that. ;)

**Comment by calxus** [comment]
I took advice from ally for the purecss, and it works quite well. Simple and effective. imo there no point to start redesigning the website now. But if others in the group fancy making this an issue on github aswell, then I won't stand in the way.

**Comment by calxus** [comment]
[x]Fix links
[x]integrate logo
[ ]fix positioning of menu/map on mobile devices
[x]upload success screen
[x]User page finished (Completed by Kaffse)
[x]Indication that the user is logged in on side menu or top bar (Completed by Kaffse)

**Comment by calxus** [comment]
I also want to tidy up the code on the pages, which shouldn't take too long

**Comment by allyjweir** [comment]
We we really need the button for selecting all recordings on the page. And the timeline on the main page

**Comment by calxus** [comment]
The button should not be a problem, but adding the timeline to the page seems to be as problem. Either only the map or the timeline ending up working. However I will spend tonight doing my best to get this functional.

**Comment by allyjweir** [comment]
The button is really key. Get it done first.

**Comment by calxus** [comment]
Will do

**Comment by calxus** [comment]
Got the select all button for the recordings done.

**Comment by calxus** [comment]
[x]Fix links
[x]integrate logo
[x]fix positioning of menu/map on mobile devices
[x]upload success screen
[x]User page finished (Completed by Kaffse)
[x]Indication that the user is logged in on side menu or top bar (Completed by Kaffse)
[x]The button is really key. Get it done first. (Going to have to tidy up my js)

Also we really need to test from data uploaded from the mobile device, so any problems can be ironed out.

**Comment by allyjweir** [comment]
I will test the application on Monday. I won't have computer access over the weekend unfortunately. Finally getting my laptop back on Sunday though so will be able to kick up spare time devel on it a little. 

I can't see any issues with the code I have for it. fingers crossed

**Comment by ppyordanov** [comment]
(y) yes only thing to make sure is we get start time in milliseconds to be able to make a proper synchronisation and it should probably be GPS time as Keir suggested. ;)

**Comment by allyjweir** [comment]
It grabs it in milliseconds. Here is the docs for the location.getTime()
method:

"Return the UTC time of this fix, in milliseconds since January 1, 1970.

Note that the UTC time on a device is not monotonic: it can jump forwards
or backwards unpredictably. So always use
getElapsedRealtimeNanos()</reference/android/location/Location.html#getElapsedRealtimeNanos()>when
calculating time deltas.

On the other hand,
getTime()</reference/android/location/Location.html#getTime()> is
useful for presenting a human readable time to the user, or for carefully
comparing location fixes across reboot or across devices.

All locations generated by the
LocationManager</reference/android/location/LocationManager.html> are
guaranteed to have a valid UTC time, however remember that the system time
may have changed since the location was generated.
Returns
- time of fix, in milliseconds since January 1, 1970."

But as it says it isn't monotonic. I will look into a lib to solve this
issue and refactor. Will have a solution for Monday!

**Comment by allyjweir** [comment]
Maybe those with android devices could pull mdrs-mobile and make a few recordings to upload to the site
