### ISSUE TITLE
Incorrect time of recording being displayed on timeline on homepage

### ISSUE THREAD

**Issue by calxus** [kaffo/multi-device-audio-project#62]
As far as I can telll the incorrect time is being displayed of when a recording has been taken.

For example from the metadata for the recording 2131099660, says it was taken on [Tue, 04 Feb 2014 15:52:10] However it is not showing this on the timeline on the homepage. It says it was taken on february the 6th at 4am

![timeline](https://f.cloud.github.com/assets/5579497/2402482/912a9354-aa22-11e3-9314-2808109f5d46.PNG)

**Comment by ppyordanov** [comment]
For me it is displayed correctly for instance if you check Lillybank jaunt: 

![alt text](http://i60.tinypic.com/28i6yhc.png)
