### ISSUE TITLE
User Accounts

### ISSUE THREAD

**Issue by calxus** [kaffo/multi-device-audio-project#8]

**Comment by allyjweir** [comment]
This needs to be sorted and integrated correctly. 2 options:

1) super basic version
2) OpenID integration.

[ ]Integrate it
[ ]Interface with user.hmtl template page to fill it out
[ ]Show indication of user logged in on the menu at left or add a new bar at the top left

**Comment by kaffo** [comment]
1. Super easy option is to basically use Django's user auth (can set that up in like 15 minutes) then have the mobile app just navigate to the server when doing any kind of user interaction. 
2. OpenID would involve us having to integrate with the OpenID API. This would mean having to edit the web app to correctly talk to this as well as building the mobile app to support it by adding user pages/recording pages.

Personally I see no reason not to go with the Django option, we decided to use a web app for a reason, so we can cut out dev time on things that are already integrated into Django.

**Comment by kaffo** [comment]
This is getting along nicely. Should have something done by the end of the weekend.

**Comment by kaffo** [comment]
Working on this now

**Comment by kaffo** [comment]
You know those moment in dev, where you sit and stare at a problem, all the code is right, all the output is right, but it just doesn't work? Yeah. That's happening.

**Comment by kaffo** [comment]
Legit got users working. Now begin the horrendous task of dragging in all that user's stuff....

**Comment by allyjweir** [comment]
Needs a couple of things

1)Needs to show username instead of user
2)Should take the user's real name as well as username
3)Needs to check if account exists already for a username while signing up
4)Logout/login/register buttons should be at the bottom of the menu. Not mixed in with the functionality ones at the top. This will make it a lot clearer to the user what it does and where to go for stuff.

**Comment by kaffo** [comment]
Everything works par adding recordings to a user's account. I can display a user's recordings but can't add them. It's rather a pain in the ass.

**Comment by kaffo** [comment]
Scratch that, got them saving properly, just not displaying
